import { mkdtemp, readdir, rm } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { spawn } from "node:child_process";
import ytDlpExec from "yt-dlp-exec";

function runCommand(command: string, args: string[]): Promise<string> {
  return new Promise((resolve, reject) => {
    const child = spawn(command, args, {
      stdio: ["ignore", "pipe", "pipe"],
      windowsHide: true,
    });

    let stdout = "";
    let stderr = "";

    child.stdout.on("data", (chunk) => {
      stdout += String(chunk);
    });

    child.stderr.on("data", (chunk) => {
      stderr += String(chunk);
    });

    child.on("error", (error) => {
      reject(error);
    });

    child.on("close", (code) => {
      if (code === 0) {
        resolve(stdout);
        return;
      }

      const details = stderr.trim() || stdout.trim() || `exit code ${code}`;
      reject(new Error(details));
    });
  });
}

export async function transcribeVideoWithLocalWhisper(
  videoId: string
): Promise<string> {
  const videoUrl = videoId.startsWith("http") 
    ? videoId 
    : `https://www.youtube.com/watch?v=${videoId}`;
  const tmpDir = await mkdtemp(path.join(os.tmpdir(), "yt-study-audio-"));

  try {
    console.log(`🎧 Downloading audio for ${videoId} via yt-dlp-exec`);
    const outputTemplate = path.join(tmpDir, "audio.%(ext)s");

    await ytDlpExec(videoUrl, {
      noPlaylist: true,
      format: "bestaudio/best",
      extractAudio: true,
      audioFormat: "wav",
      audioQuality: 0,
      output: outputTemplate,
      noWarnings: true,
      ...(process.env.YOUTUBE_COOKIES_FILE ? { cookies: process.env.YOUTUBE_COOKIES_FILE } : {})
    });

    const files = await readdir(tmpDir);
    const audioFileName = files.find((fileName) =>
      /\.(wav|mp3|m4a|webm|opus)$/i.test(fileName)
    );

    if (!audioFileName) {
      throw new Error("No audio file generated by yt-dlp");
    }

    const audioPath = path.join(tmpDir, audioFileName);
    const scriptPath = path.resolve(process.cwd(), "scripts", "transcribe_audio.py");
    const pythonBin = process.env.PYTHON_BIN || "python";
    const whisperModel = process.env.WHISPER_MODEL || "small";

    console.log(
      `🎧 Audio downloaded for ${videoId}; transcribing with Faster-Whisper model=${whisperModel}`
    );

    const args = [scriptPath, "--audio", audioPath, "--model", whisperModel];
    if (process.env.WHISPER_LANGUAGE) {
      args.push("--language", process.env.WHISPER_LANGUAGE);
    }

    const transcript = (await runCommand(pythonBin, args)).trim();

    if (!transcript) {
      throw new Error("Local transcription returned empty output");
    }

    console.log(`🎧 Local transcription output received for ${videoId}`);

    return transcript;
  } catch (error) {
    const reason = error instanceof Error ? error.message : String(error);
    throw new Error(`Local transcription failed: ${reason}`);
  } finally {
    await rm(tmpDir, { recursive: true, force: true });
  }
}
